pipeline {
  agent{
    docker{
      image 'python:rc-alpine'
  }
 }
  stages{
      stage(build){
        when{
            changeset "**/vote/**"
          }

        steps{
          echo 'Compiling vote app..'
          dir('vote'){
            sh 'python pip install -user requirements.txt'         
           }
        }
      }
      stage(vote){
        when{
          changeset "**/vote/**"
        }
        steps{
          echo 'Running Unit Tets on vote app..'
          dir('vote'){
            sh 'python tests/test_frontend.py'
           }

          }
    }
  }

  post{
    always{
        echo 'Building multibranch pipeline for vote is completed..'
    }
  }
}
