pipeline{
    agent any
    tools{
      maven 'Maven 3.6.1'
    }
    stages{
        stage(build){
            steps{
                echo 'Building worker app'
                dir('worker'){
                 sh 'mvn compile'
                }
             }
        }
        stage(two){
            steps{
                echo 'step 2'
                sleep 5
            }
        }
        stage(three){
            steps{
                echo 'step 3'
                sleep 5
            }
        }
    }
    post{
      always{
        echo 'This pipeline is completed..'
      }
   }
}
